export type SourceCategory = 'engineering' | 'security' | 'individual' | 'language' | 'misc';
export type SourceTier = 1 | 2 | 3;

export interface Source {
  name: string;
  url: string;
  category: SourceCategory;
  tier: SourceTier;
}

// Tier 1: Elite — always show
// Tier 2: Good engineering blogs
// Tier 3: Background / lower signal (many Medium pubs)

export const SOURCES: Source[] = [
  // ── SECURITY ──────────────────────────────────────────────
  { name: "Google Project Zero", url: "https://googleprojectzero.blogspot.com/feeds/posts/default", category: "security", tier: 1 },
  { name: "Trail of Bits", url: "https://blog.trailofbits.com/feed/", category: "security", tier: 1 },
  { name: "Schneier on Security", url: "https://www.schneier.com/blog/index.rdf", category: "security", tier: 1 },
  { name: "Krebs on Security", url: "https://krebsonsecurity.com/feed/", category: "security", tier: 1 },
  { name: "Google Security Blog", url: "https://feeds.feedblitz.com/google-security-blog", category: "security", tier: 1 },
  { name: "Bruce Schneier (Atom)", url: "https://www.schneier.com/blog/atom.xml", category: "security", tier: 1 },
  { name: "Filippo Valsorda", url: "https://words.filippo.io/rss/", category: "security", tier: 1 },
  { name: "Troy Hunt", url: "https://www.troyhunt.com/rss/", category: "security", tier: 2 },
  { name: "Wired Security", url: "https://www.wired.com/category/security/feed/", category: "security", tier: 2 },
  { name: "Ars Technica Security", url: "http://feeds.arstechnica.com/arstechnica/security", category: "security", tier: 2 },
  { name: "Dark Reading", url: "http://www.darkreading.com/rss_simple.asp", category: "security", tier: 2 },
  { name: "Securelist", url: "https://securelist.com/feed/", category: "security", tier: 2 },
  { name: "Naked Security", url: "https://nakedsecurity.sophos.com/feed/", category: "security", tier: 2 },
  { name: "Errata Security", url: "http://blog.erratasec.com/feeds/posts/default", category: "security", tier: 2 },
  { name: "Graham Cluley", url: "https://www.grahamcluley.com/feed", category: "security", tier: 2 },
  { name: "Malwarebytes", url: "http://blog.malwarebytes.org/feed/", category: "security", tier: 2 },
  { name: "Lawfare", url: "https://www.lawfareblog.com/taxonomy/term/5798/all/feed", category: "security", tier: 2 },
  { name: "Bohops", url: "https://bohops.com/feed/", category: "security", tier: 2 },
  { name: "Matthew Green", url: "https://blog.cryptographyengineering.com/feed/", category: "security", tier: 2 },
  { name: "Andrew Ayer", url: "https://www.agwa.name/blog/feed", category: "security", tier: 2 },
  { name: "Jessie Frazelle", url: "https://blog.jessfraz.com/index.xml", category: "security", tier: 2 },
  { name: "The State of Security", url: "http://www.tripwire.com/state-of-security/feed/", category: "security", tier: 3 },
  { name: "Team Cymru", url: "https://blog.team-cymru.org/feed/", category: "security", tier: 3 },
  { name: "WeLiveSecurity", url: "http://feeds.feedburner.com/eset/blog", category: "security", tier: 3 },
  { name: "Krypt3ia", url: "https://krypt3ia.wordpress.com/feed/", category: "security", tier: 3 },
  { name: "Roger McClinton", url: "https://www.infosecblog.org/feed/", category: "security", tier: 3 },

  // ── ELITE ENGINEERING BLOGS ────────────────────────────────
  { name: "Cloudflare Blog", url: "https://blog.cloudflare.com/rss/", category: "engineering", tier: 1 },
  { name: "Stripe Blog", url: "https://stripe.com/blog/feed.rss", category: "engineering", tier: 1 },
  { name: "Tailscale Blog", url: "https://tailscale.com/blog/index.xml", category: "engineering", tier: 1 },
  { name: "Signal Blog", url: "https://signal.org/blog/rss.xml", category: "engineering", tier: 1 },
  { name: "Oxide Computer", url: "https://oxide.computer/rss.xml", category: "engineering", tier: 1 },
  { name: "Fly.io Blog", url: "https://fly.io/blog/feed.xml", category: "engineering", tier: 1 },
  { name: "GitHub Engineering", url: "https://github.blog/engineering.atom", category: "engineering", tier: 1 },
  { name: "Hacker News", url: "http://news.ycombinator.com/rss", category: "engineering", tier: 1 },
  { name: "Stack Overflow Blog", url: "https://stackoverflow.blog/feed", category: "engineering", tier: 1 },

  // ── GOOD ENGINEERING BLOGS ─────────────────────────────────
  { name: "Netflix Tech Blog", url: "https://netflixtechblog.com/feed", category: "engineering", tier: 2 },
  { name: "Discord Engineering", url: "https://discord.com/blog/rss.xml", category: "engineering", tier: 2 },
  { name: "Shopify Engineering", url: "https://shopify.engineering/blog.atom", category: "engineering", tier: 2 },
  { name: "Dropbox Tech", url: "https://dropbox.tech/feed", category: "engineering", tier: 2 },
  { name: "Spotify Engineering", url: "https://engineering.atspotify.com/feed", category: "engineering", tier: 2 },
  { name: "DoorDash Engineering", url: "https://doordash.engineering/blog/rss", category: "engineering", tier: 2 },
  { name: "Uber Engineering", url: "https://eng.uber.com/feed/", category: "engineering", tier: 2 },
  { name: "Slack Engineering", url: "https://slack.engineering/rss", category: "engineering", tier: 2 },
  { name: "Meta Engineering", url: "https://engineering.fb.com/feed/", category: "engineering", tier: 2 },
  { name: "AWS Blog", url: "https://aws.amazon.com/blogs/aws/feed/", category: "engineering", tier: 2 },
  { name: "Vercel Blog", url: "https://vercel.com/atom", category: "engineering", tier: 2 },
  { name: "Canva Engineering", url: "https://www.canva.dev/blog/engineering/feed.xml", category: "engineering", tier: 2 },
  { name: "Grab Tech", url: "https://engineering.grab.com/feed.xml", category: "engineering", tier: 2 },
  { name: "Jane Street", url: "https://blogs.janestreet.com/feed.xml", category: "engineering", tier: 2 },
  { name: "Databricks", url: "https://www.databricks.com/feed", category: "engineering", tier: 2 },
  { name: "Timescale", url: "https://www.timescale.com/blog/rss/", category: "engineering", tier: 2 },
  { name: "Confluent", url: "https://www.confluent.io/rss.xml", category: "engineering", tier: 2 },
  { name: "Docker Blog", url: "https://www.docker.com/feed/", category: "engineering", tier: 2 },
  { name: "Mozilla Hacks", url: "https://hacks.mozilla.org/feed/", category: "engineering", tier: 2 },
  { name: "New York Times Open", url: "https://open.nytimes.com/feed", category: "engineering", tier: 2 },
  { name: "Lyft Engineering", url: "https://eng.lyft.com/feed", category: "engineering", tier: 2 },
  { name: "Indeed Engineering", url: "https://engineering.indeedblog.com/feed/", category: "engineering", tier: 2 },
  { name: "Swiggy Bytes", url: "https://bytes.swiggy.com/feed", category: "engineering", tier: 2 },
  { name: "Square Corner", url: "https://corner.squareup.com/blog/rss.xml", category: "engineering", tier: 2 },
  { name: "HubSpot Engineering", url: "https://product.hubspot.com/blog/rss.xml", category: "engineering", tier: 2 },
  { name: "Deliveroo Engineering", url: "https://deliveroo.engineering/feed.xml", category: "engineering", tier: 2 },
  { name: "Okta Developer", url: "https://developer.okta.com/feed.xml", category: "engineering", tier: 2 },
  { name: "Twilio Blog", url: "https://www.twilio.com/blog/feed", category: "engineering", tier: 2 },
  { name: "Palantir Blog", url: "https://blog.palantir.com/feed", category: "engineering", tier: 2 },
  { name: "GoDaddy Engineering", url: "https://www.godaddy.com/engineering/feed.xml", category: "engineering", tier: 2 },
  { name: "Stitch Fix Eng", url: "https://multithreaded.stitchfix.com/feed.xml", category: "engineering", tier: 2 },
  { name: "Riot Games", url: "https://technology.riotgames.com/rss.xml", category: "engineering", tier: 2 },
  { name: "RisingStack", url: "https://blog.risingstack.com/feed/", category: "engineering", tier: 2 },
  { name: "Evil Martians", url: "https://evilmartians.com/chronicles.atom", category: "engineering", tier: 2 },
  { name: "Honeybadger", url: "http://blog.honeybadger.io/blog/feed.xml", category: "engineering", tier: 2 },
  { name: "Thoughtbot", url: "https://feeds.feedburner.com/GiantRobotsSmashingIntoOtherGiantRobots", category: "engineering", tier: 2 },
  { name: "Nordic APIs", url: "https://nordicapis.com/feed/", category: "engineering", tier: 2 },
  { name: "Web Browser Engineering", url: "https://browser.engineering/rss.xml", category: "engineering", tier: 2 },
  { name: "Bun Blog", url: "https://bun.sh/rss.xml", category: "engineering", tier: 2 },
  { name: "SitePoint", url: "https://sitepoint.com/sitepoint.rss", category: "engineering", tier: 2 },
  { name: "High Scalability", url: "https://highscalability.com/rss/", category: "engineering", tier: 2 },
  { name: "Atlassian", url: "https://www.atlassian.com/blog/feed", category: "engineering", tier: 2 },
  { name: "Auth0 Blog", url: "https://auth0.com/blog/rss.xml", category: "engineering", tier: 2 },
  { name: "Khan Academy Eng", url: "http://engineering.khanacademy.org/rss", category: "engineering", tier: 2 },
  { name: "Gusto Engineering", url: "https://engineering.gusto.com/rss/", category: "engineering", tier: 2 },
  { name: "Asana Blog", url: "https://blog.asana.com/feed/", category: "engineering", tier: 2 },
  { name: "Benchling Engineering", url: "https://benchling.engineering/feed", category: "engineering", tier: 2 },
  { name: "Instacart Tech", url: "https://tech.instacart.com/feed", category: "engineering", tier: 2 },
  { name: "Honeycomb Blog", url: "https://www.honeycomb.io/blog/rss.xml", category: "engineering", tier: 2 },
  { name: "Hashnode Engineering", url: "https://engineering.hashnode.com/rss.xml", category: "engineering", tier: 2 },
  { name: "Codrops", url: "https://tympanus.net/codrops/feed/", category: "engineering", tier: 2 },
  { name: "Blender Code", url: "https://code.blender.org/rss", category: "engineering", tier: 2 },
  { name: "Serverless Blog", url: "https://www.serverless.com/blog/rss.xml", category: "engineering", tier: 2 },
  { name: "Squarespace Engineering", url: "https://engineering.squarespace.com/blog?format=rss", category: "engineering", tier: 2 },
  { name: "Stack Abuse", url: "https://stackabuse.com/rss/", category: "engineering", tier: 2 },
  { name: "Tania Rascia", url: "https://tania.dev/rss.xml", category: "engineering", tier: 2 },
  { name: "Toptal Blog", url: "https://www.toptal.com/blog.rss", category: "engineering", tier: 2 },
  // Tier 3 engineering (Medium-heavy / lower signal)
  { name: "Airbnb Engineering", url: "https://medium.com/feed/airbnb-engineering", category: "engineering", tier: 3 },
  { name: "Expedia Tech", url: "https://medium.com/feed/expedia-group-tech", category: "engineering", tier: 3 },
  { name: "Groupon Eng", url: "https://medium.com/feed/groupon-eng", category: "engineering", tier: 3 },
  { name: "Criteo Engineering", url: "https://medium.com/feed/criteo-engineering", category: "engineering", tier: 3 },
  { name: "Skyscanner Engineering", url: "https://medium.com/feed/@SkyscannerEng", category: "engineering", tier: 3 },
  { name: "Strava Engineering", url: "https://medium.com/feed/strava-engineering", category: "engineering", tier: 3 },
  { name: "Tinder Engineering", url: "https://medium.com/feed/tinder", category: "engineering", tier: 3 },
  { name: "Transferwise Engineering", url: "https://medium.com/feed/wise-engineering", category: "engineering", tier: 3 },
  { name: "Thumbtack Engineering", url: "https://medium.com/feed/thumbtack-engineering", category: "engineering", tier: 3 },
  { name: "PayPal Tech", url: "https://medium.com/feed/paypal-tech", category: "engineering", tier: 3 },
  { name: "Pinterest Engineering", url: "https://medium.com/feed/@Pinterest_Engineering", category: "engineering", tier: 3 },
  { name: "Airtable Engineering", url: "https://medium.com/feed/airtable-eng", category: "engineering", tier: 3 },
  { name: "BBC Product Tech", url: "https://medium.com/feed/bbc-product-technology", category: "engineering", tier: 3 },
  { name: "Hootsuite Engineering", url: "https://medium.com/feed/hootsuite-engineering", category: "engineering", tier: 3 },
  { name: "Harry's Engineering", url: "https://medium.com/feed/harrys-engineering", category: "engineering", tier: 3 },
  { name: "Bumble Tech", url: "https://medium.com/feed/bumble-tech", category: "engineering", tier: 3 },

  // ── INDIVIDUAL BLOGGERS ────────────────────────────────────
  { name: "Simon Willison", url: "https://simonwillison.net/atom/entries/", category: "individual", tier: 1 },
  { name: "Hillel Wayne", url: "https://www.hillelwayne.com/index.xml", category: "individual", tier: 1 },
  { name: "Cory Doctorow", url: "https://pluralistic.net/feed/", category: "individual", tier: 1 },
  { name: "Bert Hubert", url: "https://berthub.eu/articles/index.xml", category: "individual", tier: 1 },
  { name: "Terence Eden", url: "https://shkspr.mobi/blog/feed/atom/", category: "individual", tier: 1 },
  { name: "Ned Batchelder", url: "https://nedbatchelder.com/blog/rss.xml", category: "individual", tier: 1 },
  { name: "Scripting News (Dave Winer)", url: "http://scripting.com/rss.xml", category: "individual", tier: 1 },
  { name: "Robin Rendle", url: "https://robinrendle.com/feed.xml", category: "individual", tier: 1 },
  { name: "Dan Luu", url: "https://danluu.com/atom.xml", category: "individual", tier: 1 },
  { name: "Julia Evans", url: "https://jvns.ca/atom.xml", category: "individual", tier: 1 },
  { name: "Brendan Gregg", url: "http://www.brendangregg.com/blog/rss.xml", category: "individual", tier: 1 },
  { name: "Martin Fowler", url: "https://martinfowler.com/feed.atom", category: "individual", tier: 1 },
  { name: "Joel Spolsky", url: "https://www.joelonsoftware.com/feed/", category: "individual", tier: 1 },
  { name: "Jeff Atwood", url: "https://blog.codinghorror.com/rss/", category: "individual", tier: 1 },
  { name: "The Pragmatic Engineer", url: "https://blog.pragmaticengineer.com/rss/", category: "individual", tier: 1 },
  { name: "Overreacted (Dan Abramov)", url: "https://overreacted.io/rss.xml", category: "individual", tier: 1 },
  { name: "Josh Comeau", url: "https://joshwcomeau.com/rss.xml", category: "individual", tier: 1 },
  { name: "Rachel Kroll", url: "https://rachelbythebay.com/w/atom.xml", category: "individual", tier: 1 },
  { name: "Irrational Exuberance (Lethain)", url: "https://lethain.com/feeds/", category: "individual", tier: 1 },
  { name: "Bryan Cantrill", url: "https://bcantrill.dtrace.org/feed/", category: "individual", tier: 1 },
  { name: "Kyle Kingsbury (Aphyr)", url: "https://aphyr.com/posts.atom", category: "individual", tier: 1 },
  { name: "Eli Bendersky", url: "https://eli.thegreenplace.net/feeds/all.atom.xml", category: "individual", tier: 1 },
  { name: "Charity Majors", url: "https://charity.wtf/feed/", category: "individual", tier: 1 },
  { name: "Drew DeVault", url: "https://drewdevault.com/blog/index.xml", category: "individual", tier: 1 },
  { name: "George Hotz (Geohot)", url: "https://geohot.github.io/blog/feed.xml", category: "individual", tier: 1 },
  { name: "Sam Altman", url: "http://blog.samaltman.com/posts.atom", category: "individual", tier: 1 },
  { name: "Peter Norvig", url: "http://www.norvig.com/rss-feed.xml", category: "individual", tier: 1 },
  { name: "Nelson Elhage", url: "https://blog.nelhage.com/atom.xml", category: "individual", tier: 1 },
  { name: "Addy Osmani", url: "http://addyosmani.com/rss.xml", category: "individual", tier: 2 },
  { name: "Alex Russell", url: "https://infrequently.org/feed/", category: "individual", tier: 2 },
  { name: "Antirez", url: "http://antirez.com/rss", category: "individual", tier: 2 },
  { name: "Armin Ronacher", url: "http://lucumr.pocoo.org/feed.atom", category: "individual", tier: 2 },
  { name: "Axel Rauschmayer", url: "https://2ality.com/feeds/posts.atom", category: "individual", tier: 2 },
  { name: "Benedict Evans", url: "http://ben-evans.com/benedictevans?format=rss", category: "individual", tier: 2 },
  { name: "Chris Wellons", url: "http://nullprogram.com/feed/", category: "individual", tier: 2 },
  { name: "Dave Cheney", url: "https://dave.cheney.net/feed", category: "individual", tier: 2 },
  { name: "David Walsh", url: "https://davidwalsh.name/feed/atom", category: "individual", tier: 2 },
  { name: "Guido van Rossum", url: "http://neopythonic.blogspot.com/feeds/posts/default", category: "individual", tier: 2 },
  { name: "Henrik Warne", url: "https://henrikwarne.com/feed/", category: "individual", tier: 2 },
  { name: "Ilya Grigorik", url: "https://ilya.grigorik.com/essays/rss/", category: "individual", tier: 2 },
  { name: "Jake Wharton", url: "https://jakewharton.com/atom.xml", category: "individual", tier: 2 },
  { name: "Jeremy Kun", url: "https://www.jeremykun.com/index.xml", category: "individual", tier: 2 },
  { name: "Joe Nelson", url: "https://begriffs.com/atom.xml", category: "individual", tier: 2 },
  { name: "Jon Skeet", url: "https://codeblog.jonskeet.uk/feed/", category: "individual", tier: 2 },
  { name: "Julia Evans", url: "https://jvns.ca/atom.xml", category: "individual", tier: 2 },
  { name: "Lea Verou", url: "http://lea.verou.me/feed.xml", category: "individual", tier: 2 },
  { name: "Mary Rose Cook", url: "https://maryrosecook.com/blog/feed.xml", category: "individual", tier: 2 },
  { name: "Matt Might", url: "http://matt.might.net/articles/feed.rss", category: "individual", tier: 2 },
  { name: "Nick Craver", url: "https://nickcraver.com/blog/feed.xml", category: "individual", tier: 2 },
  { name: "Paul Irish", url: "https://feeds.feedburner.com/paul-irish", category: "individual", tier: 2 },
  { name: "Peteris Krumins", url: "https://catonmat.net/feed", category: "individual", tier: 2 },
  { name: "Philip Walton", url: "https://feeds.feedburner.com/philipwalton", category: "individual", tier: 2 },
  { name: "Philipp Oppermann", url: "https://os.phil-opp.com/rss.xml", category: "individual", tier: 2 },
  { name: "Raymond Chen", url: "https://devblogs.microsoft.com/oldnewthing/feed", category: "individual", tier: 2 },
  { name: "Real Python", url: "https://realpython.com/atom.xml", category: "individual", tier: 2 },
  { name: "Robert C. Martin", url: "http://blog.cleancoder.com/atom.xml", category: "individual", tier: 2 },
  { name: "Sam Newman", url: "https://samnewman.io/blog/feed.xml", category: "individual", tier: 2 },
  { name: "Scott Hanselman", url: "http://feeds.hanselman.com/ScottHanselman", category: "individual", tier: 2 },
  { name: "Sophie Alpert", url: "https://sophiebits.com/atom.xml", category: "individual", tier: 2 },
  { name: "Steve Yegge", url: "https://steve-yegge.blogspot.com/feeds/posts/default", category: "individual", tier: 2 },
  { name: "Swizec Teller", url: "https://swizec.com/rss.xml", category: "individual", tier: 2 },
  { name: "The Daily WTF", url: "https://syndication.thedailywtf.com/TheDailyWtf", category: "individual", tier: 2 },
  { name: "Vlad Mihalcea", url: "https://vladmihalcea.com/feed/", category: "individual", tier: 2 },
  { name: "Yegor Bugayenko", url: "https://www.yegor256.com/rss.xml", category: "individual", tier: 2 },
  { name: "Zach Holman", url: "https://zachholman.com/atom.xml", category: "individual", tier: 2 },
  { name: "First Round Review", url: "http://firstround.com/review/feed.xml", category: "individual", tier: 2 },
  { name: "Andrew Chen", url: "http://andrewchen.co/feed/", category: "individual", tier: 2 },
  { name: "Amjad Masad", url: "https://amasad.me/rss", category: "individual", tier: 2 },
  { name: "Jessie Frazelle", url: "https://blog.jessfraz.com/index.xml", category: "individual", tier: 2 },

  // ── LANGUAGES & FRAMEWORKS ─────────────────────────────────
  { name: "Rust Blog", url: "https://blog.rust-lang.org/feed.xml", category: "language", tier: 1 },
  { name: "Go Blog", url: "https://blog.golang.org/blog/feed.atom", category: "language", tier: 1 },
  { name: "Bun Blog", url: "https://bun.sh/rss.xml", category: "language", tier: 1 },
  { name: "IPFS Blog", url: "https://blog.ipfs.tech/index.xml", category: "language", tier: 2 },
  { name: "Kotlin Blog", url: "https://blog.jetbrains.com/kotlin/feed/", category: "language", tier: 2 },
  { name: "Laravel News", url: "https://feed.laravel-news.com/", category: "language", tier: 2 },
  { name: ".NET Blog", url: "https://devblogs.microsoft.com/dotnet/feed/", category: "language", tier: 2 },
  { name: "Microsoft Python", url: "https://devblogs.microsoft.com/python/feed/", category: "language", tier: 2 },
  { name: "Android Developers", url: "https://android-developers.googleblog.com/feeds/posts/default", category: "language", tier: 2 },
  { name: "Bootstrap Blog", url: "https://blog.getbootstrap.com/feed.xml", category: "language", tier: 2 },
  { name: "Crystal Lang", url: "https://crystal-lang.org/feed.xml", category: "language", tier: 2 },
  { name: "NSHipster", url: "http://nshipster.com/feed.xml", category: "language", tier: 2 },
  { name: "jOOQ Blog", url: "https://blog.jooq.org/feed/", category: "language", tier: 2 },
  { name: "RocksDB", url: "http://rocksdb.org/feed.xml", category: "language", tier: 2 },
  { name: "Swift Blog (Apple)", url: "https://developer.apple.com/swift/blog/news.rss", category: "language", tier: 2 },
  { name: "Nvidia Developer Blog", url: "https://developer.nvidia.com/blog/feed", category: "language", tier: 2 },

  // ── RESEARCH (ARXIV) ──────────────────────────────────────
  { name: "Arxiv: AI + ML", url: "https://rss.arxiv.org/rss/cs.AI+cs.LG", category: "misc", tier: 1 },
  { name: "Arxiv: Security", url: "https://rss.arxiv.org/rss/cs.CR", category: "security", tier: 1 },

  // ── YOUTUBE CHANNELS ───────────────────────────────────────
  { name: "Fireship", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA", category: "engineering", tier: 1 },
  { name: "Computerphile", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC9-y-6csu5WGm29I7JiwpnA", category: "engineering", tier: 2 },
  { name: "ThePrimeagen", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC8ENHE5xdFSwx71u3fDH5Xw", category: "individual", tier: 1 },
];
